const BACKEND_URL = window.FIVE_VIEW_BACKEND_URL || "https://data-structure-five-view-lab.onrender.com";
const $ = id => document.getElementById(id);
const statusEl=$("backend-status"),runButton=$("run-demo"),demoSelect=$("demo-select"),demoTitleEl=$("demo-title"),demoSubtitleEl=$("demo-subtitle");
const demoDetailsEl=$("demo-details"),themeToggle=$("theme-toggle"),themeLabel=$("theme-label"),themeIcon=$("theme-icon");
const pseudoEl=$("pseudo-output"),cEl=$("c-output"),storageEl=$("storage-output"),structureRawEl=$("pointer-output"),structureGraphEl=$("pointer-graph"),executionEl=$("execution-output"),stdoutEl=$("stdout-output");
const slider=$("snapshot-slider"),counterEl=$("snapshot-counter"),noteEl=$("snapshot-note"),prevButton=$("prev-step"),nextButton=$("next-step"),playButton=$("play-step"),speedSelect=$("play-speed");
const structureTitle=$("structure-title"),structureDescription=$("structure-description"),rendererBadge=$("renderer-badge");
let snapshots=[],runMeta={},displaySource="",playTimer=null,demos=[];
const api=path=>`${BACKEND_URL.replace(/\/$/,"")}${path}`;
const escapeHtml=text=>String(text).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const isNullPointer=value=>!value||["(nil)","0x0","0","NULL"].includes(String(value));
const shortAddress=value=>{if(isNullPointer(value))return"NULL";const s=String(value);return s.length>13?`${s.slice(0,6)}…${s.slice(-5)}`:s;};

async function checkBackend(){try{const r=await fetch(api("/health"),{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();statusEl.textContent=`后端：已连接 · v${data.version||"?"} · ${data.snapshot_schema||"schema?"}`;await loadDemos();}catch(e){console.error(e);statusEl.textContent="后端：连接失败";}}
function renderDemoOptions(data){const labels={"linked-list":"链表",array:"顺序表",stack:"栈",queue:"队列",tree:"树",graph:"图"},groups=new Map();data.forEach(d=>{if(!groups.has(d.category))groups.set(d.category,[]);groups.get(d.category).push(d);});const fragment=document.createDocumentFragment();for(const [category,items] of groups){const group=document.createElement("optgroup");group.label=labels[category]||category;items.forEach(d=>{const option=document.createElement("option");option.value=d.id;option.textContent=d.title;group.appendChild(option);});fragment.appendChild(group);}demoSelect.replaceChildren(fragment);}
async function loadDemos(){try{const r=await fetch(api("/api/demos"),{cache:"no-store"});const data=await r.json();if(!r.ok||!Array.isArray(data))return;demos=data;renderDemoOptions(data);updateDemoHeader();}catch(e){console.warn(e);}}
function renderDemoDetails(details={}){const labels={method:"操作方法",position:"操作位置",storage:"存储结构",initial:"初始状态",result:"目标结果",time:"时间复杂度",space:"辅助空间",precondition:"前置条件",key:"关键规则"};demoDetailsEl.replaceChildren(...Object.entries(labels).map(([key,label])=>{const item=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=details[key]||"—";item.append(dt,dd);return item;}));}
function updateDemoHeader(){const d=demos.find(x=>x.id===demoSelect.value);if(!d)return;demoTitleEl.textContent=d.title;demoSubtitleEl.textContent=d.subtitle||"LLDB 源码级教学实验";renderDemoDetails(d.details);setStructureHeader(d.renderer);}
function applyTheme(theme,persist=false){const next=theme==="light"?"light":"dark",isLight=next==="light";document.documentElement.dataset.theme=next;document.documentElement.style.colorScheme=next;themeToggle.setAttribute("aria-pressed",String(isLight));themeToggle.setAttribute("aria-label",isLight?"切换到深色模式":"切换到浅色模式");themeLabel.textContent=isLight?"深色模式":"浅色模式";themeIcon.textContent=isLight?"☾":"☀";if(persist){try{localStorage.setItem("five-view-theme",next);}catch(e){console.warn("无法保存主题偏好",e);}}}
function setStructureHeader(renderer){const map={"singly-linked-list":["链表指针拓扑","节点、变量指针与 next 关系同步显示"],array:["连续数组 / 顺序表","按真实连续地址显示下标、有效长度和元素搬移"],stack:["顺序栈 / Stack","从栈底到栈顶显示有效区间、top 移动与物理残留值"],"circular-queue":["循环队列 / Circular Queue","环形显示 front、rear、逻辑次序与下标回绕"],"binary-tree":["二叉搜索树 / BST","同步显示父子拓扑、当前访问节点、比较方向与递归调用栈"],graph:["图遍历 / Graph Traversal","同步显示结点状态、遍历生成树和 BFS 队列或 DFS 递归栈"]};const [title,desc]=map[renderer]||["数据结构语义视图","由专用 Renderer 解释统一 Snapshot Model"];structureTitle.textContent=title;structureDescription.textContent=desc;rendererBadge.textContent=`renderer: ${renderer||"waiting"}`;}
function resetViews(){stopPlayback();snapshots=[];runMeta={};displaySource="";pseudoEl.textContent="等待运行…";cEl.textContent="后端白名单源码";storageEl.textContent="等待运行…";structureRawEl.textContent="等待运行…";structureGraphEl.innerHTML='<div class="pointer-empty">等待运行…</div>';executionEl.textContent="等待运行…";stdoutEl.textContent="stdout: （尚无输出）";counterEl.textContent="0 / 0";slider.value=0;slider.max=0;slider.disabled=true;prevButton.disabled=nextButton.disabled=playButton.disabled=true;}
function renderSource(activeLine){const lines=displaySource.split("\n");cEl.innerHTML=lines.map((line,i)=>{const n=i+1,active=n===activeLine;return `<span class="${active?"active-source-line":""}">${active?"▶":" "} ${String(n).padStart(2," ")} | ${escapeHtml(line)}</span>`;}).join("\n");}

function renderLinkedList(snap){const heap=snap.heap||[],values=snap.values||{},pointerNames=runMeta.pointer_names||["head"];if(!heap.length){structureGraphEl.innerHTML='<div class="pointer-empty">当前没有仍存活的堆结点</div>';return;}const byAddress=new Map(heap.map(n=>[String(n.address),n])),ordered=[],visited=new Set();let cursor=values.head;while(!isNullPointer(cursor)&&byAddress.has(String(cursor))&&!visited.has(String(cursor))){const n=byAddress.get(String(cursor));ordered.push(n);visited.add(String(cursor));cursor=n.next;}for(const n of heap)if(!visited.has(String(n.address)))ordered.push(n);const width=Math.max(760,ordered.length*220+220),height=310,y=135,nodeW=140,nodeH=76,gap=80,startX=130,indexByAddr=new Map(ordered.map((n,i)=>[String(n.address),i]));const p=[`<svg viewBox="0 0 ${width} ${height}">`,'<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" class="svg-arrow-head"/></marker></defs>'];ordered.forEach((node,i)=>{const x=startX+i*(nodeW+gap);p.push(`<g class="heap-node ${String(node.address)===String(values.head)?"head-node":""}"><rect x="${x}" y="${y}" width="${nodeW}" height="${nodeH}" rx="12"/><line x1="${x+74}" y1="${y}" x2="${x+74}" y2="${y+nodeH}"/><text x="${x+37}" y="${y+30}" text-anchor="middle" class="svg-label">data</text><text x="${x+37}" y="${y+56}" text-anchor="middle" class="svg-value">${escapeHtml(node.data)}</text><text x="${x+107}" y="${y+30}" text-anchor="middle" class="svg-label">next</text><text x="${x+107}" y="${y+55}" text-anchor="middle" class="svg-address">${escapeHtml(shortAddress(node.next))}</text><text x="${x+70}" y="${y+102}" text-anchor="middle" class="svg-address">${escapeHtml(node.name)} @ ${escapeHtml(shortAddress(node.address))}</text></g>`);if(!isNullPointer(node.next)&&indexByAddr.has(String(node.next))){const tx=startX+indexByAddr.get(String(node.next))*(nodeW+gap);p.push(`<line class="svg-edge" x1="${x+nodeW}" y1="${y+38}" x2="${tx-10}" y2="${y+38}" marker-end="url(#arrow)"/>`);}else if(isNullPointer(node.next))p.push(`<text x="${x+nodeW+28}" y="${y+44}" class="svg-null">NULL</text>`);});pointerNames.forEach((name,idx)=>{const v=values[name];if(isNullPointer(v)||!indexByAddr.has(String(v)))return;const x=startX+indexByAddr.get(String(v))*(nodeW+gap)+nodeW/2,top=28+idx*24;p.push(`<text x="${x}" y="${top}" text-anchor="middle" class="svg-pointer-name ${idx?"secondary":""}">${escapeHtml(name)}</text><line class="${idx?"svg-secondary-edge":"svg-head-edge"}" x1="${x}" y1="${top+7}" x2="${x}" y2="${y-8}" marker-end="url(#arrow)"/>`);});p.push("</svg>");structureGraphEl.innerHTML=p.join("");}

function renderArray(snap){const cells=snap.array||[],v=snap.values||{};if(!cells.length){structureGraphEl.innerHTML='<div class="pointer-empty">没有数组快照</div>';return;}const cellW=118,gap=8,startX=45,y=105,width=Math.max(760,cells.length*(cellW+gap)+90),height=300;const p=[`<svg viewBox="0 0 ${width} ${height}">`];cells.forEach(cell=>{const x=startX+cell.index*(cellW+gap),active=cell.active?"array-cell-active":"array-cell-unused",focus=cell.index===v.i||cell.index===v.pos?" array-cell-focus":"";p.push(`<g class="array-cell ${active}${focus}"><text x="${x+cellW/2}" y="${y-18}" text-anchor="middle" class="array-index">[${cell.index}]</text><rect x="${x}" y="${y}" width="${cellW}" height="76" rx="10"/><text x="${x+cellW/2}" y="${y+47}" text-anchor="middle" class="array-value">${escapeHtml(cell.value)}</text><text x="${x+cellW/2}" y="${y+102}" text-anchor="middle" class="svg-address">${escapeHtml(shortAddress(cell.address))}</text></g>`);});if(Number.isInteger(v.pos)){const x=startX+v.pos*(cellW+gap)+cellW/2;p.push(`<text x="${x}" y="42" text-anchor="middle" class="svg-pointer-name">pos=${v.pos}</text><line class="svg-head-edge" x1="${x}" y1="50" x2="${x}" y2="${y-8}" marker-end="url(#arrow)"/>`);}p.push(`<text x="45" y="260" class="array-meta">length=${v.length} / capacity=${v.capacity} · 插入值=${v.value} · 当前 i=${v.i}</text></svg>`);structureGraphEl.innerHTML=p.join("");}
const RendererRegistry={"singly-linked-list":renderLinkedList,array:renderArray};
function renderStructure(snap){const renderer=runMeta.renderer||snap.model?.visualization?.renderer;setStructureHeader(renderer);(RendererRegistry[renderer]||(()=>{structureGraphEl.innerHTML='<div class="pointer-empty">该 Renderer 尚未实现</div>';}))(snap);structureRawEl.textContent=JSON.stringify(snap.model||{},null,2);}

function renderMemory(snap){const scalars=Object.entries(snap.values||{}).map(([k,v])=>`${k.padEnd(10)} ${v}`).join("\n");if(runMeta.renderer==="array"){const lines=(snap.array||[]).map(c=>`arr[${c.index}] @ ${c.address} = ${c.value}${c.active?"":"  (unused)"}`).join("\n");storageEl.textContent=`STACK / SCALARS\n${scalars}\n\nCONTIGUOUS ARRAY MEMORY\n${lines}`;return;}if(runMeta.renderer==="stack"){const lines=(snap.stack_array||[]).map(c=>`data[${c.index}] @ ${c.address} = ${c.value}${c.occupied?"  (in stack)":"  (outside top)"}`).join("\n");storageEl.textContent=`STACK / SCALARS\n${scalars}\n\nPHYSICAL STACK ARRAY\n${lines}`;return;}if(runMeta.renderer==="circular-queue"){const lines=(snap.queue||[]).map(c=>`queue[${c.index}] @ ${c.address} = ${c.value}${c.occupied?`  (logical #${c.logical_index})`:"  (free / stale)"}`).join("\n");storageEl.textContent=`STACK / SCALARS\n${scalars}\n\nPHYSICAL CIRCULAR BUFFER\n${lines}`;return;}if(runMeta.renderer==="binary-tree"){const lines=(snap.tree||[]).map(n=>`Node@${n.address}${n.detached?"  (detached)":""}\n  data=${n.data}\n  left=${n.left}\n  right=${n.right}`).join("\n\n");storageEl.textContent=`STACK / VARIABLES\n${scalars}\n\nHEAP / TREE NODES\n${lines}`;return;}if(runMeta.renderer==="graph"){const vertices=(snap.graph?.vertices||[]).map(v=>`${v.label} state[${v.id}] @ ${v.address} = ${v.state}\n  parent=${v.parent} metric=${v.metric}`).join("\n"),items=(snap.worklist?.items||[]).map(x=>`slot[${x.slot}] @ ${x.address} = ${x.vertex}${x.active?"  (active)":""}`).join("\n");storageEl.textContent=`STACK / SCALARS\n${scalars}\n\nVERTEX STATE MEMORY\n${vertices}\n\n${(snap.worklist?.kind||"worklist").toUpperCase()} MEMORY\n${items}`;return;}const stackLines=Object.entries(snap.stack||{}).map(([k,v])=>`${k.padEnd(10)} ${v}`).join("\n"),heapLines=(snap.heap||[]).map(n=>`${n.name}@${n.address}\n  data=${n.data}\n  next=${n.next}`).join("\n\n");storageEl.textContent=`MAIN STACK VARIABLES\n${stackLines||"(empty)"}\n\nHEAP\n${heapLines||"(empty)"}`;}
function updateControls(index){const enabled=snapshots.length>0;prevButton.disabled=!enabled||index<=0;nextButton.disabled=!enabled||index>=snapshots.length-1;playButton.disabled=snapshots.length<=1;}
function renderSnapshot(index){if(!snapshots.length)return;const snap=snapshots[index],dbg=snap.debugger||{};slider.value=index;counterEl.textContent=`${index+1} / ${snapshots.length}`;noteEl.textContent=snap.step;renderSource(dbg.display_source_line||0);renderMemory(snap);renderStructure(snap);const engine=runMeta.execution_engine?.startsWith("lldb")?`LLDB SOURCE BREAKPOINT ${dbg.breakpoint_hit||index+1}/${runMeta.lldb_breakpoint_hits||snapshots.length}`:`ENGINE ${runMeta.execution_engine||"unknown"}`,callStack=(dbg.call_stack||[]).map(f=>`#${f.index} ${f.function}`).join(" ← ");executionEl.textContent=`${engine}\nC LINE ${dbg.display_source_line||"?"}: ${dbg.display_source_text||""}\nframe variables: ${dbg.frame_variables_read?"已读取":"未确认"}${callStack?`\ncall stack: ${callStack}`:""}\n\nSTEP ${index+1}\n${snap.step}\n\nrenderer=${runMeta.renderer}\nschema=${runMeta.snapshot_schema||"legacy"}`;updateControls(index);}
function stopPlayback(){if(playTimer)clearInterval(playTimer);playTimer=null;playButton.textContent="▶ 自动播放";}
function moveSnapshot(delta){if(!snapshots.length)return;renderSnapshot(Math.max(0,Math.min(snapshots.length-1,Number(slider.value)+delta)));}
function togglePlayback(){if(playTimer){stopPlayback();return;}if(Number(slider.value)>=snapshots.length-1)renderSnapshot(0);playButton.textContent="Ⅱ 暂停";playTimer=setInterval(()=>{const current=Number(slider.value);if(current>=snapshots.length-1){stopPlayback();return;}renderSnapshot(current+1);},Number(speedSelect.value));}
async function runDemo(){stopPlayback();runButton.disabled=demoSelect.disabled=true;runButton.textContent="正在 Clang + LLDB 源码级调试…";try{const r=await fetch(api("/api/run-demo"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({demo_id:demoSelect.value})});const data=await r.json();if(!r.ok)throw new Error(JSON.stringify(data));runMeta=data;displaySource=data.display_source||"";snapshots=data.snapshots||[];pseudoEl.textContent=(data.pseudo||[]).join("\n");demoTitleEl.textContent=data.title||demoTitleEl.textContent;demoSubtitleEl.textContent=data.subtitle||demoSubtitleEl.textContent;renderDemoDetails(data.details);renderSource(0);stdoutEl.textContent=`${data.execution_engine} · 断点 ${data.lldb_breakpoint_hits||0} 次 · frame ${data.lldb_frame_reads||0} 组\nstdout: ${data.stdout||"（无输出）"}`;slider.disabled=snapshots.length<=1;slider.max=Math.max(0,snapshots.length-1);slider.value=0;if(snapshots.length)renderSnapshot(0);}catch(e){console.error(e);executionEl.textContent=`运行失败\n${e.message}`;}finally{runButton.disabled=demoSelect.disabled=false;runButton.textContent="再次运行当前算法";}}
slider.addEventListener("input",()=>{stopPlayback();renderSnapshot(Number(slider.value));});prevButton.addEventListener("click",()=>{stopPlayback();moveSnapshot(-1);});nextButton.addEventListener("click",()=>{stopPlayback();moveSnapshot(1);});playButton.addEventListener("click",togglePlayback);speedSelect.addEventListener("change",()=>{if(playTimer){stopPlayback();togglePlayback();}});runButton.addEventListener("click",runDemo);demoSelect.addEventListener("change",()=>{updateDemoHeader();resetViews();});themeToggle.addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="light"?"dark":"light",true));applyTheme(document.documentElement.dataset.theme);checkBackend();
