"""Priority expansion demos kept separate from API/runtime plumbing."""

AVL_SOURCE = r'''#include <stdio.h>
#include <stdlib.h>
typedef struct Node{int data,height;struct Node*left,*right;}Node;
static int h(Node*n){return n?n->height:0;}static int m(int a,int b){return a>b?a:b;}static void f(Node*n){n->height=1+m(h(n->left),h(n->right));}static Node*n(int x){Node*p=calloc(1,sizeof(Node));p->data=x;p->height=1;return p;}static Node*rr(Node*y){Node*x=y->left;y->left=x->right;x->right=y;f(y);f(x);return x;}static Node*rl(Node*x){Node*y=x->right;x->right=y->left;y->left=x;f(x);f(y);return y;}
static void out(Node*x,int*z){if(!x)return;if(!*z)printf(",");*z=0;printf("{\"address\":\"%p\",\"data\":%d,\"left\":\"%p\",\"right\":\"%p\",\"height\":%d,\"balance\":%d}",(void*)x,x->data,(void*)x->left,(void*)x->right,x->height,h(x->left)-h(x->right));out(x->left,z);out(x->right,z);}__attribute__((noinline))static void snap(const char*s,Node*root,Node*current,Node*new_node,int target,int direction){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"root\":\"%p\",\"current\":\"%p\",\"new_node\":\"%p\",\"target\":%d,\"depth\":2,\"direction\":%d},\"tree\":[",s,(void*)root,(void*)current,(void*)new_node,target,direction);int z=1;out(root,&z);printf("]}\n");}static int ok(Node*x){if(!x)return 1;int b=h(x->left)-h(x->right);return b>=-1&&b<=1&&x->height==1+m(h(x->left),h(x->right))&&ok(x->left)&&ok(x->right);}static void fr(Node*x){if(!x)return;fr(x->left);fr(x->right);free(x);}
static int ll(void){Node*root=n(30),*current=root,*new_node=n(10);int target=10,direction=-1;root->left=n(20);root->left->left=new_node;f(root->left);f(root);snap("LL 失衡：balance=+2",root,current,new_node,target,direction);root=rr(root);current=root;snap("右旋 30：LL 修复完成",root,current,new_node,target,0);int v=ok(root);fr(root);return v;}static int aa(void){Node*root=n(10),*current=root,*new_node=n(30);int target=30,direction=1;root->right=n(20);root->right->right=new_node;f(root->right);f(root);snap("RR 失衡：balance=-2",root,current,new_node,target,direction);root=rl(root);current=root;snap("左旋 10：RR 修复完成",root,current,new_node,target,0);int v=ok(root);fr(root);return v;}
static int lr(void){Node*root=n(30),*current=root,*new_node=n(20);int target=20,direction=-1;root->left=n(10);root->left->right=new_node;f(root->left);f(root);snap("LR 失衡：内侧左-右",root,current,new_node,target,direction);root->left=rl(root->left);f(root);current=root->left;snap("先左旋孩子 10",root,current,new_node,target,1);root=rr(root);current=root;snap("再右旋 30：LR 修复完成",root,current,new_node,target,0);int v=ok(root);fr(root);return v;}static int ar(void){Node*root=n(10),*current=root,*new_node=n(20);int target=20,direction=1;root->right=n(30);root->right->left=new_node;f(root->right);f(root);snap("RL 失衡：内侧右-左",root,current,new_node,target,direction);root->right=rr(root->right);f(root);current=root->right;snap("先右旋孩子 30",root,current,new_node,target,-1);root=rl(root);current=root;snap("再左旋 10：RL 修复完成",root,current,new_node,target,0);int v=ok(root);fr(root);return v;}
int main(void){setvbuf(stdout,NULL,_IONBF,0);int v=ll()+aa()+lr()+ar();printf("PROGRAM_STDOUT:avl_cases=LL RR LR RL valid=%d/4\n",v);return v==4?0:3;}'''

HEAP_SOURCE = r'''#include <stdio.h>
__attribute__((noinline))static void snap(const char*s,int*a,int size,int capacity,int current,int parent,int operation){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"size\":%d,\"capacity\":%d,\"current\":%d,\"parent\":%d,\"operation\":%d},\"array\":[",s,size,capacity,current,parent,operation);for(int i=0;i<capacity;i++){if(i)printf(",");printf("{\"index\":%d,\"address\":\"%p\",\"value\":%d,\"active\":%s}",i,(void*)&a[i],a[i],i<size?"true":"false");}printf("]}\n");}static void sw(int*a,int i,int j){int t=a[i];a[i]=a[j];a[j]=t;}static int ok(int*a,int n){for(int i=1;i<n;i++)if(a[(i-1)/2]<a[i])return 0;return 1;}
int main(void){setvbuf(stdout,NULL,_IONBF,0);int a[8]={20,5,15,22,9},size=5,capacity=8,current=1,parent=0,operation=0;snap("原数组尚未满足最大堆序",a,size,capacity,current,parent,operation);sw(a,1,3);snap("建堆：5 与 22 交换",a,size,capacity,3,1,operation);sw(a,0,1);snap("建堆：20 与 22 交换，最大堆完成",a,size,capacity,1,0,operation);operation=1;a[size]=30;current=size;parent=2;size++;snap("插入 30 到数组末尾",a,size,capacity,current,parent,operation);sw(a,5,2);current=2;parent=0;snap("30 与父结点 15 交换",a,size,capacity,current,parent,operation);sw(a,2,0);current=0;parent=-1;snap("30 上浮到堆顶",a,size,capacity,current,parent,operation);operation=2;int removed=a[0];a[0]=a[--size];current=0;snap("删除堆顶：末元素 15 移到根",a,size,capacity,current,parent,operation);sw(a,0,2);current=2;parent=0;snap("15 与 22 交换并下沉完成",a,size,capacity,current,parent,operation);int v=ok(a,size);printf("PROGRAM_STDOUT:removed=%d max=22 valid=%d\n",removed,v);return v?0:3;}'''

DSU_SOURCE = r'''#include <stdio.h>
#define N 8
static int fd(int*p,int x){return p[x]==x?x:(p[x]=fd(p,p[x]));}static void un(int*p,int*r,int a,int b){a=fd(p,a);b=fd(p,b);if(a==b)return;if(r[a]<r[b]){int t=a;a=b;b=t;}p[b]=a;if(r[a]==r[b])r[a]++;}__attribute__((noinline))static void snap(const char*s,int*parent,int*rank,int current,int root_a,int root_b,int operation){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"capacity\":8,\"current\":%d,\"root_a\":%d,\"root_b\":%d,\"operation\":%d},\"dsu\":[",s,current,root_a,root_b,operation);for(int i=0;i<N;i++){if(i)printf(",");printf("{\"index\":%d,\"address\":\"%p\",\"parent\":%d,\"rank\":%d}",i,(void*)&parent[i],parent[i],rank[i]);}printf("]}\n");}
int main(void){setvbuf(stdout,NULL,_IONBF,0);int parent[N],rank[N]={0},current=-1,root_a=-1,root_b=-1,operation=0;for(int i=0;i<N;i++)parent[i]=i;snap("初始化：每个元素各自成集",parent,rank,current,root_a,root_b,operation);un(parent,rank,0,1);current=1;operation=1;snap("union(0,1)：等秩合并",parent,rank,current,0,1,operation);un(parent,rank,2,3);current=3;snap("union(2,3)",parent,rank,current,2,3,operation);un(parent,rank,0,2);current=2;snap("union(0,2)：按秩合并",parent,rank,current,0,2,operation);un(parent,rank,4,5);un(parent,rank,6,7);un(parent,rank,4,6);current=7;snap("构造第二棵高度为 2 的集合树",parent,rank,current,4,6,operation);un(parent,rank,0,4);snap("合并两棵等秩集合树",parent,rank,7,0,4,operation);operation=2;root_a=parent[7];snap("find(7) 前：路径 7→6→4→0",parent,rank,7,root_a,root_b,operation);root_a=fd(parent,7);root_b=fd(parent,5);snap("路径压缩：查询路径直接指向根 0",parent,rank,7,root_a,root_b,operation);printf("PROGRAM_STDOUT:find7=%d find5=%d parent7=%d\n",root_a,root_b,parent[7]);return root_a||root_b?3:0;}'''

TRIE_SOURCE = r'''#include <stdio.h>
#define MAX 16
typedef struct{int child[3],parent,terminal;char ch;}Node;
__attribute__((noinline))static void snap(const char*s,Node*nodes,int node_count,int current,int word_index,int char_index,int status){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"node_count\":%d,\"current\":%d,\"word_index\":%d,\"char_index\":%d,\"status\":%d},\"trie\":{\"nodes\":[",s,node_count,current,word_index,char_index,status);for(int i=0;i<node_count;i++){if(i)printf(",");printf("{\"id\":%d,\"address\":\"%p\",\"char\":\"%c\",\"parent\":%d,\"terminal\":%s}",i,(void*)&nodes[i],i?nodes[i].ch:'^',nodes[i].parent,nodes[i].terminal?"true":"false");}printf("],\"edges\":[");int f=1;for(int i=0;i<node_count;i++)for(int c=0;c<3;c++)if(nodes[i].child[c]){if(!f)printf(",");f=0;printf("{\"from\":%d,\"to\":%d,\"char\":\"%c\"}",i,nodes[i].child[c],'a'+c);}printf("]}}\n");}static int add(Node*n,int*c,int p,int x){int i=(*c)++;n[i].parent=p;n[i].ch='a'+x;n[p].child[x]=i;return i;}
int main(void){setvbuf(stdout,NULL,_IONBF,0);Node nodes[MAX]={0};nodes[0].parent=-1;int node_count=1,current=0,word_index=0,char_index=0,status=0;snap("初始化空 Trie 根结点",nodes,node_count,current,word_index,char_index,status);current=add(nodes,&node_count,0,0);snap("插入 ab：创建 a",nodes,node_count,current,word_index,0,status);current=add(nodes,&node_count,current,1);nodes[current].terminal=1;snap("插入 ab：创建 b 并标记结尾",nodes,node_count,current,word_index,1,1);word_index=1;current=nodes[0].child[0];snap("插入 ac：复用公共前缀 a",nodes,node_count,current,word_index,0,0);current=add(nodes,&node_count,current,2);nodes[current].terminal=1;snap("插入 ac：创建 c 并标记结尾",nodes,node_count,current,word_index,1,1);word_index=2;current=add(nodes,&node_count,0,1);snap("插入 ba：根下创建 b",nodes,node_count,current,word_index,0,0);current=add(nodes,&node_count,current,0);nodes[current].terminal=1;snap("插入 ba：创建 a 并标记结尾",nodes,node_count,current,word_index,1,1);word_index=3;current=0;snap("搜索 ac：从根开始",nodes,node_count,current,word_index,0,0);current=nodes[current].child[0];snap("搜索 ac：沿 a 边继续",nodes,node_count,current,word_index,1,0);current=nodes[current].child[2];status=nodes[current].terminal;snap("搜索 ac 命中；前缀 a 也存在",nodes,node_count,current,word_index,2,status);printf("PROGRAM_STDOUT:words=ab,ac,ba search_ac=%d prefix_a=1 nodes=%d\n",status,node_count);return status?0:3;}'''

RB_DELETE_SOURCE = r'''#include <stdio.h>
#include <stdlib.h>
typedef enum{BLACK,RED}Color;typedef struct Node{int data;Color color;struct Node*left,*right,*parent;}Node;static Node*g_root,*g_current,*g_new_node;static int g_target,g_case;static Node*n(int d,Color c){Node*x=calloc(1,sizeof(Node));x->data=d;x->color=c;return x;}static void L(Node*p,Node*c){p->left=c;if(c)c->parent=p;}static void R(Node*p,Node*c){p->right=c;if(c)c->parent=p;}static void rotl(Node**r,Node*x){Node*y=x->right;x->right=y->left;if(y->left)y->left->parent=x;y->parent=x->parent;if(!x->parent)*r=y;else if(x==x->parent->left)x->parent->left=y;else x->parent->right=y;L(y,x);}static void rotr(Node**r,Node*x){Node*y=x->left;x->left=y->right;if(y->right)y->right->parent=x;y->parent=x->parent;if(!x->parent)*r=y;else if(x==x->parent->left)x->parent->left=y;else x->parent->right=y;R(y,x);}
static void out(Node*x,int*f){if(!x)return;if(!*f)printf(",");*f=0;printf("{\"address\":\"%p\",\"data\":%d,\"color\":\"%s\",\"left\":\"%p\",\"right\":\"%p\",\"parent\":\"%p\"}",(void*)x,x->data,x->color==RED?"red":"black",(void*)x->left,(void*)x->right,(void*)x->parent);out(x->left,f);out(x->right,f);}__attribute__((noinline))static void snap(const char*s){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"root\":\"%p\",\"current\":\"%p\",\"new_node\":\"%p\",\"target\":%d,\"depth\":1,\"direction\":0,\"case_code\":%d},\"tree\":[",s,(void*)g_root,(void*)g_current,(void*)g_new_node,g_target,g_case);int f=1;out(g_root,&f);printf("]}\n");}static int bh(Node*x){if(!x)return 1;int a=bh(x->left),b=bh(x->right);if(!a||a!=b||(x->color==RED&&((x->left&&x->left->color==RED)||(x->right&&x->right->color==RED))))return 0;return a+(x->color==BLACK);}static int ok(Node*r){return r&&r->color==BLACK&&bh(r)>0;}static void fr(Node*x){if(!x)return;fr(x->left);fr(x->right);free(x);}
static int c1(void){Node*p=n(10,BLACK),*s=n(20,RED),*a=n(15,BLACK),*b=n(25,BLACK);R(p,s);L(s,a);R(s,b);g_root=p;g_current=p;g_new_node=s;g_target=5;g_case=100;snap("红兄弟：删除黑叶后产生双黑");s->color=BLACK;p->color=RED;rotl(&g_root,p);g_case=101;g_new_node=a;snap("交换颜色并左旋父结点");a->color=RED;p->color=BLACK;g_case=102;snap("黑兄弟无红孩子：由红父吸收双黑");int v=ok(g_root);fr(g_root);return v;}static int c2(void){Node*p=n(10,BLACK),*s=n(20,BLACK);R(p,s);g_root=p;g_current=p;g_new_node=s;g_target=5;g_case=110;snap("黑兄弟且两个侄子均黑");s->color=RED;g_case=111;snap("兄弟染红，双黑上推到根并消除");int v=ok(g_root);fr(g_root);return v;}
static int c3(void){Node*p=n(10,BLACK),*s=n(20,BLACK),*q=n(15,RED);R(p,s);L(s,q);g_root=p;g_current=p;g_new_node=s;g_target=5;g_case=120;snap("近侄红、远侄黑");q->color=BLACK;s->color=RED;rotr(&g_root,s);g_new_node=q;g_case=121;snap("右旋兄弟，转换为远侄红");q->color=BLACK;p->color=BLACK;s->color=BLACK;rotl(&g_root,p);g_case=122;g_current=g_root;snap("左旋父结点，双黑修复完成");int v=ok(g_root);fr(g_root);return v;}static int c4(void){Node*p=n(10,BLACK),*s=n(20,BLACK),*q=n(25,RED);R(p,s);R(s,q);g_root=p;g_current=p;g_new_node=s;g_target=5;g_case=130;snap("远侄为红，可直接旋转");s->color=BLACK;q->color=BLACK;rotl(&g_root,p);g_case=131;g_current=g_root;snap("左旋父结点并重染色，双黑消除");int v=ok(g_root);fr(g_root);return v;}int main(void){setvbuf(stdout,NULL,_IONBF,0);int v=c1()+c2()+c3()+c4();printf("PROGRAM_STDOUT:rb_delete_cases=4 valid=%d/4\n",v);return v==4?0:3;}'''

TREAP_SOURCE = r'''#include <stdio.h>
#include <stdlib.h>
typedef struct Node{int data,priority;struct Node*left,*right;}Node;static Node*n(int d,int p){Node*x=calloc(1,sizeof(Node));x->data=d;x->priority=p;return x;}static Node*rr(Node*y){Node*x=y->left;y->left=x->right;x->right=y;return x;}static Node*rl(Node*x){Node*y=x->right;x->right=y->left;y->left=x;return y;}static void out(Node*x,int*f){if(!x)return;if(!*f)printf(",");*f=0;printf("{\"address\":\"%p\",\"data\":%d,\"priority\":%d,\"left\":\"%p\",\"right\":\"%p\"}",(void*)x,x->data,x->priority,(void*)x->left,(void*)x->right);out(x->left,f);out(x->right,f);}__attribute__((noinline))static void snap(const char*s,Node*root,Node*current,Node*new_node,int target,int direction){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"root\":\"%p\",\"current\":\"%p\",\"new_node\":\"%p\",\"target\":%d,\"depth\":2,\"direction\":%d},\"tree\":[",s,(void*)root,(void*)current,(void*)new_node,target,direction);int f=1;out(root,&f);printf("]}\n");}static int ok(Node*x,int lo,int hi,int p){return !x||(x->data>lo&&x->data<hi&&x->priority>=p&&ok(x->left,lo,x->data,x->priority)&&ok(x->right,x->data,hi,x->priority));}static void fr(Node*x){if(!x)return;fr(x->left);fr(x->right);free(x);}
int main(void){setvbuf(stdout,NULL,_IONBF,0);Node*root=n(30,80),*current=root,*new_node=NULL;int target=30,direction=0;snap("初始 Treap：30/80",root,current,new_node,target,direction);new_node=n(20,60);root->left=new_node;target=20;direction=-1;snap("BST 插入 20，违反优先级堆序",root,root,new_node,target,direction);root=rr(root);current=root;snap("右旋 30：20 上浮",root,current,new_node,target,0);new_node=n(40,70);root->right->right=new_node;target=40;direction=1;snap("BST 插入 40，违反父结点优先级",root,root->right,new_node,target,direction);root->right=rl(root->right);snap("左旋 30：40 上浮",root,root->right,new_node,target,0);new_node=n(25,50);root->right->left->left=new_node;target=25;direction=-1;snap("插入 25/50：准备连续上浮",root,root->right->left,new_node,target,direction);root->right->left=rr(root->right->left);snap("右旋 30",root,root->right->left,new_node,target,0);root->right=rr(root->right);snap("右旋 40",root,root->right,new_node,target,0);root=rl(root);current=root;snap("左旋 20：25 成为根，双重不变量恢复",root,current,new_node,target,0);int v=ok(root,-999,999,-1);printf("PROGRAM_STDOUT:inorder=20,25,30,40 heap_order=%d\n",v);fr(root);return v?0:3;}'''

HASH_SOURCE = r'''#include <stdio.h>
#define N 7
__attribute__((noinline))static void snap(const char*s,int*keys,int*vals,int*state,int capacity,int length,int key,int probe,int mode,int status){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"capacity\":%d,\"length\":%d,\"key\":%d,\"probe\":%d,\"mode\":%d,\"status\":%d},\"hash\":[",s,capacity,length,key,probe,mode,status);for(int i=0;i<capacity;i++){if(i)printf(",");printf("{\"index\":%d,\"address\":\"%p\",\"key\":%d,\"value\":%d,\"state\":%d}",i,(void*)&keys[i],keys[i],vals[i],state[i]);}printf("]}\n");}
int main(void){setvbuf(stdout,NULL,_IONBF,0);int keys[N]={0},vals[N]={0},state[N]={0},capacity=N,length=0,key=10,probe=3,mode=1,status=0;keys[3]=10;vals[3]=100;state[3]=1;length++;snap("线性探测：10 写入 h=3",keys,vals,state,capacity,length,key,probe,mode,status);key=17;status=1;snap("17 在下标 3 冲突",keys,vals,state,capacity,length,key,probe,mode,status);probe=4;keys[4]=17;state[4]=1;length++;status=0;snap("线性探测到下标 4",keys,vals,state,capacity,length,key,probe,mode,status);key=24;probe=5;keys[5]=24;state[5]=1;length++;snap("24 经 3、4 写入 5",keys,vals,state,capacity,length,key,probe,mode,status);key=17;probe=4;state[4]=2;length--;status=2;snap("删除 17：保留 TOMBSTONE",keys,vals,state,capacity,length,key,probe,mode,status);key=31;keys[4]=31;state[4]=1;length++;status=0;snap("31 复用墓碑 4",keys,vals,state,capacity,length,key,probe,mode,status);for(int i=0;i<N;i++)keys[i]=state[i]=0;length=0;mode=2;key=10;probe=3;keys[3]=10;state[3]=1;length++;snap("二次探测：10 位于 3",keys,vals,state,capacity,length,key,probe,mode,0);key=17;probe=4;keys[4]=17;state[4]=1;length++;snap("17 的序列 3→4",keys,vals,state,capacity,length,key,probe,mode,0);key=24;probe=0;keys[0]=24;state[0]=1;length++;snap("24 的序列 3→4→0",keys,vals,state,capacity,length,key,probe,mode,0);printf("PROGRAM_STDOUT:linear tombstone quadratic_slots=3,4,0\n");return 0;}'''

SEGMENT_SOURCE = r'''#include <stdio.h>
typedef struct Node{int l,r,sum;struct Node*left,*right;}Node;static Node t[7];static void out(Node*x,int*f){if(!x)return;if(!*f)printf(",");*f=0;printf("{\"address\":\"%p\",\"data\":%d,\"left\":\"%p\",\"right\":\"%p\",\"range\":\"[%d,%d]\",\"sum\":%d}",(void*)x,x->sum,(void*)x->left,(void*)x->right,x->l,x->r,x->sum);out(x->left,f);out(x->right,f);}__attribute__((noinline))static void snap(const char*s,Node*root,Node*current,Node*new_node,int target,int depth,int direction){printf("SNAPSHOT:{\"step\":\"%s\",\"values\":{\"root\":\"%p\",\"current\":\"%p\",\"new_node\":\"%p\",\"target\":%d,\"depth\":%d,\"direction\":%d},\"tree\":[",s,(void*)root,(void*)current,(void*)new_node,target,depth,direction);int f=1;out(root,&f);printf("]}\n");}
int main(void){setvbuf(stdout,NULL,_IONBF,0);Node*root=&t[0],*current=root,*new_node=NULL;int target=0,depth=0,direction=0;t[0]=(Node){0,3,11,&t[1],&t[2]};t[1]=(Node){0,1,3,&t[3],&t[4]};t[2]=(Node){2,3,8,&t[5],&t[6]};t[3]=(Node){0,0,2,0,0};t[4]=(Node){1,1,1,0,0};t[5]=(Node){2,2,5,0,0};t[6]=(Node){3,3,3,0,0};snap("建树完成：根 [0,3] sum=11",root,current,new_node,target,depth,direction);target=1;current=&t[1];depth=1;direction=-1;snap("查询 [1,3]：访问左子树",root,current,new_node,target,depth,direction);current=&t[4];depth=2;snap("取叶 [1,1]=1",root,current,new_node,target,depth,direction);current=&t[2];depth=1;direction=1;target=9;snap("整段命中 [2,3]=8，结果为 9",root,current,new_node,target,depth,direction);target=6;current=&t[5];depth=2;direction=0;t[5].sum=6;snap("更新 index=2：5→6",root,current,new_node,target,depth,direction);current=&t[2];depth=1;t[2].sum=9;snap("回溯更新 [2,3] sum=9",root,current,new_node,target,depth,direction);current=root;depth=0;t[0].sum=12;snap("回溯更新根 sum=12",root,current,new_node,target,depth,direction);printf("PROGRAM_STDOUT:query=9 update=6 root_sum=%d\n",root->sum);return root->sum==12?0:3;}'''

TREE_DISPLAY = """insert_by_key();
inspect_metadata();
rotate_and_refresh();
assert(structure_invariant());
"""
RB_DELETE_DISPLAY = """delete_black_node();
while (double_black && node != root) {
    inspect_sibling_and_nephews();
    recolor_or_rotate();
}
assert(red_black_properties());
"""
HEAP_DISPLAY = """build_max_heap(data);
push_heap(30);
removed = data[0];
data[0] = data[--size];
sift_down(0);
"""
HASH_DISPLAY = """insert_linear(10, 17, 24);
erase(17);          // TOMBSTONE
insert_linear(31);  // reuse tombstone
insert_quadratic(10, 17, 24);
"""
DSU_DISPLAY = """make_set(0..7);
union_by_rank(a, b);
root = find(7);
parent[x] = find(parent[x]);
"""
SEGMENT_DISPLAY = """build(0, 3);
result = query(1, 3);
update(2, 6);
sum[node] = sum[left] + sum[right];
"""
TRIE_DISPLAY = """insert("ab");
insert("ac");
insert("ba");
found = search("ac");
prefix = starts_with("a");
"""

def _demo(title, subtitle, category, renderer, source, display, count, texts, frame_vars, pseudo, **extra):
    return {"title":title,"subtitle":subtitle,"category":category,"renderer":renderer,"source":source,"display_source":display,"display_stage_lines":list(range(1,count+1)),"display_stage_text":texts,"frame_vars":frame_vars,"pseudo":pseudo,"breakpoint_mode":"snap-caller",**extra}

EXTENDED_DEMOS = {
    "avl-rotation-cases": _demo("AVL 树：LL、RR、LR、RL 四类旋转","高度、平衡因子和单/双旋同步变化","tree","binary-tree",AVL_SOURCE,TREE_DISPLAY,10,["LL 失衡","LL 右旋","RR 失衡","RR 左旋","LR 失衡","左旋孩子","右旋祖父","RL 失衡","右旋孩子","左旋祖父"],["root","current","new_node","target","direction"],["1. 构造 LL、RR、LR、RL 三结点失衡","2. 外侧失衡执行单旋","3. 内侧失衡执行双旋","4. 每次旋转刷新 height/balance","5. 验证四种结果均满足 |balance|≤1"],tree_mode="avl",pointer_names=["root","current","new_node"]),
    "red-black-tree-delete-cases": _demo("红黑树：删除双黑修复分支","红兄弟、黑兄弟、近侄红、远侄红四种路径","tree","red-black-tree",RB_DELETE_SOURCE,RB_DELETE_DISPLAY,10,["红兄弟","旋转转换","吸收双黑","黑兄弟","上推双黑","近侄红","旋转兄弟","旋转父亲","远侄红","完成修复"],["g_root","g_current","g_new_node","g_target","g_case"],["1. 删除黑结点后产生双黑","2. 红兄弟先换色旋转","3. 黑兄弟双黑侄时上推","4. 近侄红先转换为远侄红","5. 远侄红旋父并重染色消除双黑"],tree_mode="red-black-delete",pointer_names=["root","current","new_node"]),
    "treap-insert-rotations": _demo("Treap：确定优先级插入与连续旋转","同时维持 BST 键序和最小堆优先级","tree","binary-tree",TREAP_SOURCE,TREE_DISPLAY,9,["初始","插入20","右旋","插入40","左旋","插入25","右旋30","右旋40","左旋20"],["root","current","new_node","target","direction"],["1. 按 BST 键序插入","2. 使用固定优先级保证可复现","3. 子结点优先级更小时旋转上浮","4. 插入 25 触发连续旋转","5. 验证 BST 与堆序双重不变量"],tree_mode="treap",pointer_names=["root","current","new_node"]),
    "binary-max-heap-operations": _demo("二叉最大堆：建堆、插入与删除堆顶","数组下标与完全二叉树父子关系同步显示","heap","binary-heap",HEAP_SOURCE,HEAP_DISPLAY,8,["初始数组","下沉1","下沉0","末尾插入","第一次上浮","上浮到根","替换堆顶","下沉完成"],["a","size","capacity","current","parent","operation"],["1. 自底向上调整为最大堆","2. 插入 30 并连续上浮","3. 删除堆顶并以末元素补根","4. 选择较大孩子下沉","5. 验证父结点不小于孩子"]),
    "open-address-hash-table": _demo("开放定址哈希表：线性/二次探测与墓碑","冲突路径、删除标记和槽位复用逐帧显示","hash","hash-table",HASH_SOURCE,HASH_DISPLAY,9,["插入10","冲突17","线性探测","插入24","墓碑删除","复用墓碑","二次探测10","二次探测17","二次探测24"],["keys","vals","state","capacity","length","key","probe","mode","status"],["1. 线性探测插入冲突键","2. 删除时留下 TOMBSTONE","3. 新键复用首个墓碑","4. 演示二次探测 h+i²","5. 区分三种槽位状态"]),
    "union-find-rank-compression": _demo("并查集：按秩合并与路径压缩","parent/rank 双数组和集合树同步显示","set","union-find",DSU_SOURCE,DSU_DISPLAY,8,["初始化","union01","union23","合并","第二棵树","等秩合并","压缩前","压缩后"],["parent","rank","current","root_a","root_b","operation"],["1. 初始化 8 个独立集合","2. 等秩合并时提升 rank","3. 低秩根挂到高秩根","4. 构造 7→6→4→0 路径","5. find 回溯并压缩整条路径"]),
    "segment-tree-query-update": _demo("线段树：建树、区间查询与单点更新","区间、聚合值和回溯更新同步显示","range","binary-tree",SEGMENT_SOURCE,SEGMENT_DISPLAY,7,["建树","拆分查询","叶结点","整段命中","更新叶","更新父","更新根"],["root","current","new_node","target","depth","direction"],["1. 从 [2,1,5,3] 建立区间和树","2. 查询 [1,3] 得到 9","3. index=2 从 5 更新为 6","4. 沿父链回算区间和","5. 根和从 11 更新为 12"],tree_mode="segment-tree",pointer_names=["root","current","new_node"]),
    "trie-insert-search-prefix": _demo("Trie 字典树：插入、搜索与前缀匹配","公共前缀复用、字符边与终止标记同步显示","string","trie",TRIE_SOURCE,TRIE_DISPLAY,10,["根","创建a","完成ab","复用a","完成ac","创建b","完成ba","搜索根","沿a","命中ac"],["nodes","node_count","current","word_index","char_index","status"],["1. 初始化空根结点","2. 插入 ab、ac 并复用前缀 a","3. 插入 ba 建立另一分支","4. 搜索 ac 逐字符沿边前进","5. terminal 区分完整单词与前缀"]),
}

_LINE_MAPS = {
    "avl-rotation-cases":[1,3,1,3,1,3,3,1,3,3],
    "red-black-tree-delete-cases":[1,3,4,1,4,3,4,4,3,4],
    "treap-insert-rotations":[1,3,3,1,3,1,3,3,3],
    "binary-max-heap-operations":[1,1,1,2,2,2,3,5],
    "open-address-hash-table":[1,1,1,1,2,3,4,4,4],
    "union-find-rank-compression":[1,2,2,2,2,2,3,4],
    "segment-tree-query-update":[1,2,2,2,3,4,4],
    "trie-insert-search-prefix":[1,1,1,2,2,3,3,4,4,5],
}
for _id, _lines in _LINE_MAPS.items():
    EXTENDED_DEMOS[_id]["display_stage_lines"] = _lines

EXTENDED_DETAILS = {
    "avl-rotation-cases":{"method":"AVL 四类旋转修复","position":"最小失衡子树根","storage":"带 height/balance 的链式树","initial":"四个独立失衡树","result":"LL/RR/LR/RL 全部恢复平衡","time":"插入 O(log n)","space":"O(1) 局部旋转","precondition":"旋转前满足 BST 次序","key":"旋转后自底向上刷新高度"},
    "red-black-tree-delete-cases":{"method":"红黑树删除双黑修复","position":"双黑结点、兄弟与侄结点","storage":"带 parent/color 的链式树","initial":"四种经典局部结构","result":"双黑消除且性质恢复","time":"O(log n)","space":"O(1)","precondition":"删除前为合法红黑树","key":"红兄弟先转换；近侄转远侄；远侄旋转收尾"},
    "treap-insert-rotations":{"method":"BST 插入 + 堆序旋转","position":"新结点祖先链","storage":"带 priority 的链式树","initial":"30/80","result":"根 25/50；中序 20,25,30,40","time":"期望 O(log n)","space":"O(1)","precondition":"优先级固定且唯一","key":"旋转同时维持键序和最小堆序"},
    "binary-max-heap-operations":{"method":"建堆、上浮、下沉","position":"完全二叉树数组下标","storage":"连续数组","initial":"[20,5,15,22,9]","result":"删除 30 后最大值 22","time":"建堆 O(n)，更新 O(log n)","space":"O(1)","precondition":"容量足够","key":"parent=(i-1)/2，children=2i+1/2i+2"},
    "open-address-hash-table":{"method":"线性/二次探测与墓碑删除","position":"h(key) 探测序列","storage":"固定槽位数组","initial":"7 个空槽","result":"冲突处理、墓碑复用、二次探测","time":"平均 O(1)，最坏 O(n)","space":"O(1)","precondition":"装载因子受控","key":"删除不能直接改 EMPTY"},
    "union-find-rank-compression":{"method":"按秩合并 + 路径压缩","position":"根与 find 路径","storage":"parent/rank 双数组","initial":"8 个单元素集合","result":"合并为一个集合并压缩查询路径","time":"摊还 O(α(n))","space":"O(n)","precondition":"编号合法","key":"只有根的 rank 有意义"},
    "segment-tree-query-update":{"method":"区间查询 + 单点更新","position":"闭区间树结点","storage":"链式教学树","initial":"[2,1,5,3]，根和 11","result":"query=9，更新后根和 12","time":"O(log n)","space":"O(n)","precondition":"区间合法","key":"整段命中直接返回，更新沿路径回算"},
    "trie-insert-search-prefix":{"method":"逐字符插入、搜索、前缀匹配","position":"根到字符路径","storage":"结点数组 + child[3]","initial":"空 Trie","result":"保存 ab/ac/ba，命中 ac 与前缀 a","time":"O(|word|)","space":"O(字符总数)","precondition":"字符限 a/b/c","key":"共享前缀只建一次，terminal 表示完整单词"},
}
